### ISSUE TITLE
How to support go-micro 1.0 or 3.0 or 3.1?

### ISSUE THREAD

**Issue by anotherGoogleFan** [asim/protoc-gen-go-micro#74]
I update this tool and only to find the import path is github.com/micro/go-micro/v2/xxxxx, not github.com/asim/go-micro/xxxx or github.com/micro/go-micro/xxxx. 
My project is using go-micro 1.X and will update to 3.1 soon. 
How to support the version go-micro 1.X or 3.1 using this tool?

**Comment by asim** [comment]
go-micro v1 and v2 were hosted at github.com/micro/go-micro. So these are all preserved in that way and github will redirect as appropriate. For v3 I'll switch out the paths.

**Comment by anotherGoogleFan** [comment]
Thanks for your answer. Hope the v3 support come soon.
